// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWUn00qSFZzZLPvoTNO5cnQx7k0jh6yA',
    appId: '1:434633013833:web:a00b10aaeeb75f3898dd98',
    messagingSenderId: '434633013833',
    projectId: 'community-3873a',
    authDomain: 'community-3873a.firebaseapp.com',
    storageBucket: 'community-3873a.firebasestorage.app',
    measurementId: 'G-C3HXLVH28W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ5_H4n7edm85jmzy43lVxIkhS6JfLmqM',
    appId: '1:434633013833:android:fb2f11b6043e62fd98dd98',
    messagingSenderId: '434633013833',
    projectId: 'community-3873a',
    storageBucket: 'community-3873a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTh1Bfv9zPCBfxS3h_G92d5iVp4Q1V5vM',
    appId: '1:434633013833:ios:a9f30996a1b6c86698dd98',
    messagingSenderId: '434633013833',
    projectId: 'community-3873a',
    storageBucket: 'community-3873a.firebasestorage.app',
    iosBundleId: 'com.example.community',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhWUn00qSFZzZLPvoTNO5cnQx7k0jh6yA',
    appId: '1:434633013833:web:6ba9a93286b544ea98dd98',
    messagingSenderId: '434633013833',
    projectId: 'community-3873a',
    authDomain: 'community-3873a.firebaseapp.com',
    storageBucket: 'community-3873a.firebasestorage.app',
    measurementId: 'G-4H6VCHD9VT',
  );
}
